### ISSUE TITLE
Incorrect integration instructions in website documentation for FacebookCore 0.7.0

### ISSUE THREAD

**Issue by joshuafinch** [facebook/facebook-swift-sdk#463]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-swift-sdk/issues)
- [x] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment

- Xcode Version: `10.2.1`
- Swift Version: `5.0`
- Installation Platform & Version: `CocoaPods` version `1.7.1`

## Goals

Attempting to upgrade the framework from version `0.6.0` to `0.7.0`, and compiling the application successfully.

## Expected Results

When upgrading from `0.6.0` to `0.7.0`, and following the instructions on the Facebook Documentation to be able to compile the application, with the framework successfully.

Instructions followed here:
https://developers.facebook.com/docs/swift/getting-started

## Actual Results

Code fails to compile with the following errors:

> Use of unresolved identifier 'SDKApplicationDelegate'; did you mean 'UIApplicationDelegate'?

> Use of unresolved identifier 'AppEventsLogger'

## Steps to Reproduce

1. Existing codebase that uses `FacebookCore` version `0.6.0` installed via CocoaPods only.
2. `pod update FacebookCore` to version `0.7.0`
3. Observe compilation errors due to missing identifiers

## Code Samples & Details

With just `FacebookCore` imported, the identifiers for `AppEventsLogger`, and `SDKApplicationDelegate` are no longer available in version `0.7.0`, and unable to find the suitable alternatives.

```swift
import Foundation
import UIKit
import FacebookCore

class AppDelegate: UIResponder, UIApplicationDelegate {

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {

        SDKApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)

        // Additional app delegate setup code...

         return true
    }

    func applicationDidBecomeActive(_ application: UIApplication) {
        AppEventsLogger.activate(application)
    }

    func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool {
        return SDKApplicationDelegate.shared.application(app, open: url, options: options)
    }
}
```

**Comment by aehlke** [comment]
See https://github.com/facebook/facebook-swift-sdk/issues/439

**Comment by NeverwinterMoon** [comment]
@joshuafinch Just check out the changes made in the Samples/Catalog of the project. Or just this commit: https://github.com/facebook/facebook-swift-sdk/commit/335ad2c0dd0d277759046a1e4b0d87643ca176e1

This clearly outlines all the required changed when updating to 0.7

**Comment by joshuafinch** [comment]
Thanks, @aehlke, @NeverwinterMoon - using the sample code worked.

Would be good to get the main documentation on the website here updated to match, as that was the initial point of confusion as to why these types no longer existed.

https://developers.facebook.com/docs/swift/getting-started

**Comment by Aquima** [comment]
hi  use this code:
 ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)

**Comment by joesus** [comment]
There is more detail in #439 to explain what happened and please see the changelog [here](https://github.com/facebook/facebook-objc-sdk/blob/master/CHANGELOG.md#500). There is admittedly work to do regarding the documentation for this SDK; however, this is not a bug. Closing.
